
(function(){var e=null;function f(a){if(a!=e)return escape(a.toString());return""}function h(a){if(a!=e)return a.toString().substring(0,256);return""}function j(a,b){var g=f(b);if(g!=""){var c=f(a);if(c!="")return"&".concat(c,"=",g)}return""}function k(a){var b=typeof a;if(a==e||b=="object"||b=="function")return e;return String(a).replace(/,/g,"\\,").replace(/;/g,"\\;").replace(/=/g,"\\=")}
function l(a){var b;a=a.google_custom_params;if(!a||typeof a!="object"||a instanceof Array)b="";else{var g=[];for(b in a){var c=a[b];if(c instanceof Array){for(var d=[],i=0;i<c.length;++i){var q=k(c[i]);q!=e&&d.push(q)}c=d.length==0?e:d.join(",")}else c=k(c);(d=k(b))&&c!=e&&g.push(d+"="+c)}b=g.join(";")}if(b=="")return"";return"&".concat("data=",encodeURIComponent(b))}function m(a){if(typeof a!="number"&&typeof a!="string")return"";return f(a.toString())}
function n(a){if(!a)return"";a=a.google_conversion_items;if(!a)return"";for(var b=[],g=0,c=a.length;g<c;g++){var d=a[g],i=[];d&&(i.push(m(d.value)),i.push(m(d.quantity)),i.push(m(d.item_id)),i.push(m(d.adwords_grouping)),i.push(m(d.sku)),b.push("("+i.join("*")+")"))}return b.length>0?"&item="+b.join(""):""}
function o(a,b,g){var c=[];if(a){var d=a.screen;d&&(c.push(j("u_h",d.height)),c.push(j("u_w",d.width)),c.push(j("u_ah",d.availHeight)),c.push(j("u_aw",d.availWidth)),c.push(j("u_cd",d.colorDepth)));a.history&&c.push(j("u_his",a.history.length))}g&&typeof g.getTimezoneOffset=="function"&&c.push(j("u_tz",-g.getTimezoneOffset()));b&&(typeof b.javaEnabled=="function"&&c.push(j("u_java",b.javaEnabled())),b.plugins&&c.push(j("u_nplug",b.plugins.length)),b.mimeTypes&&c.push(j("u_nmime",b.mimeTypes.length)));
return c.join("")}function p(a,b){var g="";if(b){var c=b.referrer;if(a&&a.top&&b.location&&a.top.location==b.location)g+=j("ref",h(c)),c=b.location;g+=j("url",h(c))}return g}function r(a){if(a&&a.location&&a.location.protocol&&a.location.protocol.toString().toLowerCase()=="https:")return"https:";return"http:"}function s(a){if(a.google_remarketing_only)return"googleads.g.doubleclick.net";return a.google_conversion_domain||"www.googleadservices.com"}
function t(a){var b=navigator,g=document,c="/?";a.google_conversion_type=="landing"&&(c="/extclk?");var d;d=a.google_remarketing_only?"viewthroughconversion/":"conversion/";c=r(a)+"//"+s(a)+"/pagead/"+[d,f(a.google_conversion_id),c,"random=",f(a.google_conversion_time)].join("");a:{d=a.google_conversion_language;if(d!=e){d=d.toString();if(2==d.length){d=j("hl",d);break a}if(5==d.length){d=j("hl",d.substring(0,2))+j("gl",d.substring(3,5));break a}}d=""}c+=[j("cv",a.google_conversion_js_version),j("fst",
a.google_conversion_first_time),j("num",a.google_conversion_snippets),j("fmt",a.google_conversion_format),j("value",a.google_conversion_value),j("label",a.google_conversion_label),j("oid",a.google_conversion_order_id),j("bg",a.google_conversion_color),d,j("guid","ON"),j("disvt",a.google_disable_viewthrough),n(a),o(a,b,a.google_conversion_date),p(a,g),l(a)].join("");return c}
function u(a){if({ar:1,bg:1,cs:1,da:1,de:1,el:1,en_AU:1,en_US:1,en_GB:1,es:1,et:1,fi:1,fr:1,hi:1,hr:1,hu:1,id:1,is:1,it:1,iw:1,ja:1,ko:1,lt:1,nl:1,no:1,pl:1,pt_BR:1,pt_PT:1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tl:1,tr:1,vi:1,zh_CN:1,zh_TW:1}[a])return a+".html";return"en_US.html"}
function v(){var a=w,b=t(a),g=function(a,b,g){return'<img height="'+g+'" width="'+b+'" border="0" src="'+a+'" />'};return a.google_conversion_format==0&&a.google_conversion_domain==e?'<a href="'+(r(a)+"//services.google.com/sitestats/"+u(a.google_conversion_language)+"?cid="+f(a.google_conversion_id))+'" target="_blank">'+g(b,135,27)+"</a>":a.google_conversion_snippets>1||a.google_conversion_format==3?g(b,1,1):'<iframe name="google_conversion_frame" width="'+(a.google_conversion_format==2?200:300)+
'" height="'+(a.google_conversion_format==2?26:13)+'" src="'+b+'" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no">'+g(b.replace(/\?random=/,"?frame=0&random="),1,1)+"</iframe>"}
function x(){var a=w;if(a.google_conversion_type=="landing"||!a.google_conversion_id)return!1;if(a.google_remarketing_only&&a.google_disable_viewthrough)return!1;a.google_conversion_date=new Date;a.google_conversion_time=a.google_conversion_date.getTime();typeof a.google_conversion_snippets=="number"&&a.google_conversion_snippets>0?a.google_conversion_snippets+=1:a.google_conversion_snippets=1;typeof a.google_conversion_first_time!="number"&&(a.google_conversion_first_time=a.google_conversion_time);
a.google_conversion_js_version="6";a.google_conversion_format!=0&&a.google_conversion_format!=1&&a.google_conversion_format!=2&&a.google_conversion_format!=3&&(a.google_conversion_format=1);return!0};var w=window;
if(w)if(/[\?&;]google_debug/.exec(document.URL)!=e){var y=document.getElementsByTagName("head")[0];y||(y=document.createElement("head"),document.getElementsByTagName("html")[0].insertBefore(y,document.getElementsByTagName("body")[0]));var z=document.createElement("script");z.src=r(window)+"//"+s(window)+"/pagead/conversion_debug_overlay.js";y.appendChild(z)}else{try{x()&&document.write(v())}catch(A){}var B=w;B.google_conversion_date=e;B.google_conversion_time=e;B.google_conversion_js_version=e;B.google_conversion_id=
e;B.google_conversion_value=e;B.google_conversion_label=e;B.google_conversion_language=e;B.google_conversion_format=e;B.google_conversion_color=e;B.google_conversion_type=e;B.google_conversion_order_id=e;B.google_conversion_items=e;B.google_custom_params=e;B.google_conversion_domain=e;B.google_disable_viewthrough=e;B.google_remarketing_only=e};})();
